name: Deploy to dev

on:
  repository_dispatch:
    types:
      - deploy-dev

jobs:
  # Build and Deploy Job
  build-and-deploy:
    runs-on: ubuntu-24.04
    environment:
      name: dev
      url: https://public-lead-submission-test.dev.am-i.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        env:
          VITE_SITE_KEY: ${{ secrets.VITE_SITE_KEY }}
          VITE_API_ENDPOINT: ${{ vars.VITE_API_ENDPOINT }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
